[package]
name = "engine"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
vcpkg = ["sdl2/static-link", "sdl2/use-vcpkg"]
pkgconfig = ["sdl2/use-pkgconfig"]
portmaster = []
browser = []

[dependencies]
rand.workspace = true
rand_chacha.workspace = true
serde.workspace = true
sdl2.workspace = true
ab_glyph.workspace = true
image.workspace = true
confy.workspace = true
num-format.workspace = true
symphonia.workspace = true
strum.workspace = true
strum_macros.workspace = true
