pub mod recording;
mod apply_inputs;
mod input_search;
pub mod input_sequence;
pub mod action_evaluator;
mod board_features;
pub mod agent;
mod headless_game;
pub mod genetic;
mod game_result;
mod mutation;
mod generation_stats;
mod coefficient;
pub mod neural;
mod genome;
pub mod linear;
mod generation_record;
mod organism;
mod objective;

